[package]
name = "axum-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.6" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
